### PR TITLE
Fix macOS 15.4+ build issues with strchrnul

### PR DESCRIPTION
**Pull request by mistyhey**
## Summary

This PR fixes build failures on macOS 15.4+ caused by the `strchrnul` function availability issue in PostgreSQL dependencies.

## Problem

When building sqlc on macOS 15.4+, the build fails with the error:
```
src_port_snprintf.c:374:1: error: static declaration of 'strchrnul' follows non-static declaration
```

This occurs because:
- macOS 15.4 introduced `strchrnul` as a system function
- PostgreSQL's embedded code includes its own implementation
- The conflicting declarations cause compilation to fail

## Solution

Added conditional build flags in the Makefile that:
1. Detect macOS version at build time
2. For macOS 15.4+, set `MACOSX_DEPLOYMENT_TARGET=15.4` and `CGO_CFLAGS="-DHAVE_STRCHRNUL"`
3. This tells PostgreSQL's code that `strchrnul` is available, preventing the duplicate definition

Also fixed a related issue in the release script where the version variable path was incorrect.

## Changes
- Modified `Makefile` to add macOS version detection and conditional build flags
- Fixed version variable path in `scripts/release.go` from `internal/cmd.version` to `internal/info.Version`

## Testing
- Successfully builds on macOS 15.4+
- Maintains compatibility with older macOS versions

## Build Error Before Fix
Xnip2025-09-09_10-37-30

### CODE REVIEW

File: internal/codegen/golang/driver.go [hunk 1]
```diff
@@ -16,7 +16,7 @@ const (
 	SQLDriverPGXV5                      = "github.com/jackc/pgx/v5"
 	SQLDriverLibPQ                      = "github.com/lib/pq"
 	SQLDriverGoSQLDriverMySQL           = "github.com/go-sql-driver/mysql"
-	SQLDriverWPGX                       = "github.com/stumble/wpgx"
+	SQLDriverWPGX                       = "github.com/one2x-ai/wpgx"
```
Comment (Stumble) [inline internal/codegen/golang/driver.go]: For this PR, we need to revert this back to github.com/stumble/wpgx

File: internal/codegen/golang/imports.go [hunk 2]
```diff
@@ -496,7 +496,7 @@ func (i *importer) batchImports() fileImports {
 	case SQLDriverPGXV5:
 		pkg[ImportSpec{Path: "github.com/jackc/pgx/v5"}] = struct{}{}
 	case SQLDriverWPGX:
-		pkg[ImportSpec{Path: "github.com/stumble/wpgx"}] = struct{}{}
+		pkg[ImportSpec{Path: "github.com/one2x-ai/wpgx"}] = struct{}{}
 	}
```
Comment (Stumble) [inline internal/codegen/golang/imports.go]: same here

**Review by Stumble — COMMENTED** [review]
Thanks for the PR. Some minor while critial changes required.

**Comment by mistyhey** [comment]
done reverting dependencies.

**Review by Stumble — APPROVED** [review]

**Comment by Stumble** [comment]
xiexie xinlu

**Comment by mistyhey** [comment]
@Stumble 时隔多年, 还是被老夏罩住了好吗
